### ISSUE TITLE
Move examples into dedicated folder

### ISSUE THREAD

**Issue by asongtoruin** [JackMcKew/pandas-alive#3]
The repo is currently a little messy with the examples stored at the root - moving these into an `examples` folder (and updating the readme accordingly) would help tidy this up a bit.

**Comment by JackMcKew** [comment]
This is fixed in: https://github.com/JackMcKew/pandas-alive/commit/8ab095648764dbd053fef95109cf21eba1b08168

Thanks for the suggestion!
